name: Test minimo

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".github/workflows/test.yml"]

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hola mundo"
